name: Post

on:
  repository_dispatch:
    types: [new-post]

jobs:
  create_post:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Append new post
      run: |-
        pip install -r requirements.txt
        echo "${{ github.event.client_payload.text }}" | python thread.py
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
